import Foundation
import InlineSnapshotTesting
import Path
import Testing
import XcodeGraph
import XcodeProj
import XcodeProjMapper

extension IntegrationTests {
    @Test("Maps an iOS app with extensions into the correct graph")
    func iosAppWithExtensions() throws {
        try assertGraph {
            .iosAppWithExtensions
        } name: {
            """
            - "App"

            """
        } dependencies: {
            """
            ▿ 3 key/value pairs
              ▿ (2 elements)
                ▿ key: target 'App'
                  ▿ target: (3 elements)
                    - name: "App"
                    - path: /Fixtures/ios_app_with_extensions
                    - status: LinkingStatus.required
                ▿ value: 4 members
                  ▿ target 'AppIntentExtension'
                    ▿ target: (3 elements)
                      - name: "AppIntentExtension"
                      - path: /Fixtures/ios_app_with_extensions
                      - status: LinkingStatus.required
                  ▿ target 'NotificationServiceExtension'
                    ▿ target: (3 elements)
                      - name: "NotificationServiceExtension"
                      - path: /Fixtures/ios_app_with_extensions
                      - status: LinkingStatus.required
                  ▿ target 'StickersPackExtension'
                    ▿ target: (3 elements)
                      - name: "StickersPackExtension"
                      - path: /Fixtures/ios_app_with_extensions
                      - status: LinkingStatus.required
                  ▿ target 'WidgetExtension'
                    ▿ target: (3 elements)
                      - name: "WidgetExtension"
                      - path: /Fixtures/ios_app_with_extensions
                      - status: LinkingStatus.required
              ▿ (2 elements)
                ▿ key: target 'AppWithMessagesExtension'
                  ▿ target: (3 elements)
                    - name: "AppWithMessagesExtension"
                    - path: /Fixtures/ios_app_with_extensions
                    - status: LinkingStatus.required
                ▿ value: 2 members
                  ▿ target 'MessageExtension'
                    ▿ target: (3 elements)
                      - name: "MessageExtension"
                      - path: /Fixtures/ios_app_with_extensions
                      - status: LinkingStatus.required
                  ▿ target 'NotificationServiceExtension'
                    ▿ target: (3 elements)
                      - name: "NotificationServiceExtension"
                      - path: /Fixtures/ios_app_with_extensions
                      - status: LinkingStatus.required
              ▿ (2 elements)
                ▿ key: target 'WidgetExtension'
                  ▿ target: (3 elements)
                    - name: "WidgetExtension"
                    - path: /Fixtures/ios_app_with_extensions
                    - status: LinkingStatus.required
                ▿ value: 2 members
                  ▿ target 'Bundle'
                    ▿ target: (3 elements)
                      - name: "Bundle"
                      - path: /Fixtures/ios_app_with_extensions
                      - status: LinkingStatus.required
                  ▿ target 'StaticFramework'
                    ▿ target: (3 elements)
                      - name: "StaticFramework"
                      - path: /Fixtures/ios_app_with_extensions
                      - status: LinkingStatus.required

            """
        } dependencyConditions: {
            """
            - 0 key/value pairs

            """
        } packages: {
            """
            - 0 key/value pairs

            """
        } workspace: {
            """
            ▿ Workspace
              - additionalFiles: 0 elements
              ▿ generationOptions: GenerationOptions
                ▿ autogeneratedWorkspaceSchemes: AutogeneratedWorkspaceSchemes
                  ▿ enabled: (5 elements)
                    - codeCoverageMode: CodeCoverageMode.disabled
                    ▿ testingOptions: TestingOptions
                      - rawValue: 0
                    - testLanguage: Optional<String>.none
                    - testRegion: Optional<String>.none
                    - testScreenCaptureFormat: Optional<ScreenCaptureFormat>.none
                ▿ enableAutomaticXcodeSchemes: Optional<Bool>
                  - some: false
                - lastXcodeUpgradeCheck: Optional<Version>.none
                - renderMarkdownReadme: false
              - ideTemplateMacros: Optional<IDETemplateMacros>.none
              - name: "App"
              - path: /Fixtures/ios_app_with_extensions
              ▿ projects: 1 element
                - /Fixtures/ios_app_with_extensions/App.xcodeproj
              - schemes: 0 elements
              - xcWorkspacePath: /Fixtures/ios_app_with_extensions/App.xcworkspace

            """
        } projects: {
            """
            ▿ 1 key/value pair
              ▿ (2 elements)
                - key: /Fixtures/ios_app_with_extensions/App.xcodeproj
                ▿ value: App
                  - path: /Fixtures/ios_app_with_extensions
                  - sourceRootPath: /Fixtures/ios_app_with_extensions
                  - xcodeProjPath: /Fixtures/ios_app_with_extensions
                  - name: "App"
                  - organizationName: Optional<String>.none
                  - classPrefix: Optional<String>.none
                  ▿ defaultKnownRegions: Optional<Array<String>>
                    ▿ some: 2 elements
                      - "Base"
                      - "en"
                  ▿ developmentRegion: Optional<String>
                    - some: "en"
                  ▿ options: Options
                    - automaticSchemesOptions: AutomaticSchemesOptions.disabled
                    - disableBundleAccessors: false
                    - disableShowEnvironmentVarsInScriptPhases: false
                    - disableSynthesizedResourceAccessors: false
                    ▿ textSettings: TextSettings
                      - indentWidth: Optional<UInt>.none
                      - tabWidth: Optional<UInt>.none
                      - usesTabs: Optional<Bool>.none
                      - wrapsLines: Optional<Bool>.none
                  ▿ targets: 9 key/value pairs
                    ▿ (2 elements)
                      - key: "App"
                      ▿ value: Target
                        ▿ additionalFiles: 23 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/AppIntentExtension/Sources/AppIntentExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/AppIntentExtension/Sources/AppIntentExtensionExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Bundle/dummy.jpg
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/AppIntentExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/Bundle-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/MessageExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/NotificationServiceExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/StaticFramework-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/StickersPackExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/WidgetExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistAssets+MessageExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistAssets+WidgetExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistBundle+MessageExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistBundle+WidgetExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Resources/Base.lproj/MainInterface.storyboard/Base.lproj/MainInterface.storyboard
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Sources/MessagesViewController.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/NotificationServiceExtension/NotificationService.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/StaticFramework/Sources/StaticFramework.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/StickersPackExtension/Stickers.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/WidgetExtension/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/WidgetExtension/Sources/Widget.swift
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.App"
                        ▿ copyFiles: 3 elements
                          ▿ CopyFilesAction
                            - destination: Destination.productsDirectory
                            - files: 0 elements
                            - name: "Embed ExtensionKit Extensions"
                            ▿ subpath: Optional<String>
                              - some: "$(EXTENSIONS_FOLDER_PATH)"
                          ▿ CopyFilesAction
                            - destination: Destination.plugins
                            - files: 0 elements
                            - name: "Embed Foundation Extensions"
                            - subpath: Optional<String>.none
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                        - coreDataModels: 0 elements
                        ▿ dependencies: 4 elements
                          ▿ TargetDependency
                            ▿ target: (3 elements)
                              - name: "AppIntentExtension"
                              - status: LinkingStatus.required
                              - condition: Optional<PlatformCondition>.none
                          ▿ TargetDependency
                            ▿ target: (3 elements)
                              - name: "NotificationServiceExtension"
                              - status: LinkingStatus.required
                              - condition: Optional<PlatformCondition>.none
                          ▿ TargetDependency
                            ▿ target: (3 elements)
                              - name: "StickersPackExtension"
                              - status: LinkingStatus.required
                              - condition: Optional<PlatformCondition>.none
                          ▿ TargetDependency
                            ▿ target: (3 elements)
                              - name: "WidgetExtension"
                              - status: LinkingStatus.required
                              - condition: Optional<PlatformCondition>.none
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "App"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: application
                        - productName: "App"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          - resources: 0 elements
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        ▿ sources: 2 elements
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/ios_app_with_extensions/Sources/AppDelegate.swift
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/ios_app_with_extensions/Sources/Documentation.docc
                    ▿ (2 elements)
                      - key: "AppIntentExtension"
                      ▿ value: Target
                        ▿ additionalFiles: 23 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Bundle/dummy.jpg
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/AppIntentExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/Bundle-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/MessageExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/NotificationServiceExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/StaticFramework-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/StickersPackExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/WidgetExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistAssets+MessageExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistAssets+WidgetExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistBundle+MessageExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistBundle+WidgetExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Resources/Base.lproj/MainInterface.storyboard/Base.lproj/MainInterface.storyboard
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Sources/MessagesViewController.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/NotificationServiceExtension/NotificationService.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Sources/AppDelegate.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Sources/Documentation.docc
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/StaticFramework/Sources/StaticFramework.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/StickersPackExtension/Stickers.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/WidgetExtension/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/WidgetExtension/Sources/Widget.swift
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.App.AppIntentExtension"
                        ▿ copyFiles: 1 element
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                        - coreDataModels: 0 elements
                        - dependencies: 0 elements
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "AppIntentExtension"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: extensionKit extension
                        - productName: "AppIntentExtension"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          - resources: 0 elements
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        ▿ sources: 2 elements
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/ios_app_with_extensions/AppIntentExtension/Sources/AppIntentExtension.swift
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/ios_app_with_extensions/AppIntentExtension/Sources/AppIntentExtensionExtension.swift
                    ▿ (2 elements)
                      - key: "AppWithMessagesExtension"
                      ▿ value: Target
                        ▿ additionalFiles: 23 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/AppIntentExtension/Sources/AppIntentExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/AppIntentExtension/Sources/AppIntentExtensionExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Bundle/dummy.jpg
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/AppIntentExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/Bundle-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/MessageExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/NotificationServiceExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/StaticFramework-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/StickersPackExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/WidgetExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistAssets+MessageExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistAssets+WidgetExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistBundle+MessageExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistBundle+WidgetExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Resources/Base.lproj/MainInterface.storyboard/Base.lproj/MainInterface.storyboard
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Sources/MessagesViewController.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/NotificationServiceExtension/NotificationService.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/StaticFramework/Sources/StaticFramework.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/StickersPackExtension/Stickers.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/WidgetExtension/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/WidgetExtension/Sources/Widget.swift
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.App2"
                        ▿ copyFiles: 2 elements
                          ▿ CopyFilesAction
                            - destination: Destination.plugins
                            - files: 0 elements
                            - name: "Embed Foundation Extensions"
                            - subpath: Optional<String>.none
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                        - coreDataModels: 0 elements
                        ▿ dependencies: 2 elements
                          ▿ TargetDependency
                            ▿ target: (3 elements)
                              - name: "MessageExtension"
                              - status: LinkingStatus.required
                              - condition: Optional<PlatformCondition>.none
                          ▿ TargetDependency
                            ▿ target: (3 elements)
                              - name: "NotificationServiceExtension"
                              - status: LinkingStatus.required
                              - condition: Optional<PlatformCondition>.none
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "AppWithMessagesExtension"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: application
                        - productName: "AppWithMessagesExtension"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          - resources: 0 elements
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        ▿ sources: 2 elements
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/ios_app_with_extensions/Sources/AppDelegate.swift
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/ios_app_with_extensions/Sources/Documentation.docc
                    ▿ (2 elements)
                      - key: "Bundle"
                      ▿ value: Target
                        ▿ additionalFiles: 24 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/AppIntentExtension/Sources/AppIntentExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/AppIntentExtension/Sources/AppIntentExtensionExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/AppIntentExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/Bundle-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/MessageExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/NotificationServiceExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/StaticFramework-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/StickersPackExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/WidgetExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistAssets+MessageExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistAssets+WidgetExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistBundle+MessageExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistBundle+WidgetExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Resources/Base.lproj/MainInterface.storyboard/Base.lproj/MainInterface.storyboard
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Sources/MessagesViewController.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/NotificationServiceExtension/NotificationService.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Sources/AppDelegate.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Sources/Documentation.docc
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/StaticFramework/Sources/StaticFramework.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/StickersPackExtension/Stickers.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/WidgetExtension/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/WidgetExtension/Sources/Widget.swift
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.App.Bundle"
                        ▿ copyFiles: 1 element
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                        - coreDataModels: 0 elements
                        - dependencies: 0 elements
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "Bundle"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: bundle
                        - productName: "Bundle"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          ▿ resources: 1 element
                            ▿ ResourceFileElement
                              ▿ file: (3 elements)
                                - path: /Fixtures/ios_app_with_extensions/Bundle/dummy.jpg
                                - tags: 0 elements
                                - inclusionCondition: Optional<PlatformCondition>.none
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        - sources: 0 elements
                    ▿ (2 elements)
                      - key: "MessageExtension"
                      ▿ value: Target
                        ▿ additionalFiles: 21 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/AppIntentExtension/Sources/AppIntentExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/AppIntentExtension/Sources/AppIntentExtensionExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Bundle/dummy.jpg
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/AppIntentExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/Bundle-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/MessageExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/NotificationServiceExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/StaticFramework-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/StickersPackExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/WidgetExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistAssets+WidgetExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistBundle+WidgetExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Resources/Base.lproj/MainInterface.storyboard/Base.lproj/MainInterface.storyboard
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/NotificationServiceExtension/NotificationService.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Sources/AppDelegate.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Sources/Documentation.docc
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/StaticFramework/Sources/StaticFramework.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/StickersPackExtension/Stickers.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/WidgetExtension/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/WidgetExtension/Sources/Widget.swift
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.App2.MessageExtension"
                        ▿ copyFiles: 1 element
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                        - coreDataModels: 0 elements
                        - dependencies: 0 elements
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "MessageExtension"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: iMessage extension
                        - productName: "MessageExtension"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          ▿ resources: 2 elements
                            ▿ ResourceFileElement
                              ▿ file: (3 elements)
                                - path: /Fixtures/ios_app_with_extensions/MessageExtension/Resources/Assets.xcassets
                                - tags: 0 elements
                                - inclusionCondition: Optional<PlatformCondition>.none
                            ▿ ResourceFileElement
                              ▿ file: (3 elements)
                                - path: /Fixtures/ios_app_with_extensions/MessageExtension/Resources/Base.lproj/MainInterface.storyboard/Base.lproj/MainInterface.storyboard
                                - tags: 0 elements
                                - inclusionCondition: Optional<PlatformCondition>.none
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        ▿ sources: 3 elements
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistAssets+MessageExtension.swift
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistBundle+MessageExtension.swift
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/ios_app_with_extensions/MessageExtension/Sources/MessagesViewController.swift
                    ▿ (2 elements)
                      - key: "NotificationServiceExtension"
                      ▿ value: Target
                        ▿ additionalFiles: 24 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/AppIntentExtension/Sources/AppIntentExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/AppIntentExtension/Sources/AppIntentExtensionExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Bundle/dummy.jpg
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/AppIntentExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/Bundle-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/MessageExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/NotificationServiceExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/StaticFramework-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/StickersPackExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/WidgetExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistAssets+MessageExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistAssets+WidgetExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistBundle+MessageExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistBundle+WidgetExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Resources/Base.lproj/MainInterface.storyboard/Base.lproj/MainInterface.storyboard
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Sources/MessagesViewController.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Sources/AppDelegate.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Sources/Documentation.docc
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/StaticFramework/Sources/StaticFramework.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/StickersPackExtension/Stickers.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/WidgetExtension/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/WidgetExtension/Sources/Widget.swift
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.App.NotificationServiceExtension"
                        ▿ copyFiles: 1 element
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                        - coreDataModels: 0 elements
                        - dependencies: 0 elements
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "NotificationServiceExtension"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: app extension
                        - productName: "NotificationServiceExtension"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          - resources: 0 elements
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        ▿ sources: 1 element
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/ios_app_with_extensions/NotificationServiceExtension/NotificationService.swift
                    ▿ (2 elements)
                      - key: "StaticFramework"
                      ▿ value: Target
                        ▿ additionalFiles: 24 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/AppIntentExtension/Sources/AppIntentExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/AppIntentExtension/Sources/AppIntentExtensionExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Bundle/dummy.jpg
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/AppIntentExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/Bundle-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/MessageExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/NotificationServiceExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/StaticFramework-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/StickersPackExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/WidgetExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistAssets+MessageExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistAssets+WidgetExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistBundle+MessageExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistBundle+WidgetExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Resources/Base.lproj/MainInterface.storyboard/Base.lproj/MainInterface.storyboard
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Sources/MessagesViewController.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/NotificationServiceExtension/NotificationService.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Sources/AppDelegate.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Sources/Documentation.docc
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/StickersPackExtension/Stickers.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/WidgetExtension/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/WidgetExtension/Sources/Widget.swift
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.App.StaticFramework"
                        ▿ copyFiles: 1 element
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                        - coreDataModels: 0 elements
                        - dependencies: 0 elements
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "StaticFramework"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: dynamic framework
                        - productName: "StaticFramework"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          - resources: 0 elements
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        ▿ sources: 1 element
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/ios_app_with_extensions/StaticFramework/Sources/StaticFramework.swift
                    ▿ (2 elements)
                      - key: "StickersPackExtension"
                      ▿ value: Target
                        ▿ additionalFiles: 24 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/AppIntentExtension/Sources/AppIntentExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/AppIntentExtension/Sources/AppIntentExtensionExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Bundle/dummy.jpg
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/AppIntentExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/Bundle-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/MessageExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/NotificationServiceExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/StaticFramework-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/StickersPackExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/WidgetExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistAssets+MessageExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistAssets+WidgetExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistBundle+MessageExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistBundle+WidgetExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Resources/Base.lproj/MainInterface.storyboard/Base.lproj/MainInterface.storyboard
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Sources/MessagesViewController.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/NotificationServiceExtension/NotificationService.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Sources/AppDelegate.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Sources/Documentation.docc
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/StaticFramework/Sources/StaticFramework.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/WidgetExtension/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/WidgetExtension/Sources/Widget.swift
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.App.StickersPackExtension"
                        ▿ copyFiles: 1 element
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                        - coreDataModels: 0 elements
                        - dependencies: 0 elements
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "StickersPackExtension"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: sticker pack extension
                        - productName: "StickersPackExtension"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          ▿ resources: 1 element
                            ▿ ResourceFileElement
                              ▿ file: (3 elements)
                                - path: /Fixtures/ios_app_with_extensions/StickersPackExtension/Stickers.xcassets
                                - tags: 0 elements
                                - inclusionCondition: Optional<PlatformCondition>.none
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        - sources: 0 elements
                    ▿ (2 elements)
                      - key: "WidgetExtension"
                      ▿ value: Target
                        ▿ additionalFiles: 21 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/AppIntentExtension/Sources/AppIntentExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/AppIntentExtension/Sources/AppIntentExtensionExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Bundle/dummy.jpg
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/AppIntentExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/Bundle-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/MessageExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/NotificationServiceExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/StaticFramework-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/StickersPackExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/InfoPlists/WidgetExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistAssets+MessageExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistBundle+MessageExtension.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Resources/Base.lproj/MainInterface.storyboard/Base.lproj/MainInterface.storyboard
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/MessageExtension/Sources/MessagesViewController.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/NotificationServiceExtension/NotificationService.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Sources/AppDelegate.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/Sources/Documentation.docc
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/StaticFramework/Sources/StaticFramework.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_extensions/StickersPackExtension/Stickers.xcassets
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.App.WidgetExtension"
                        ▿ copyFiles: 2 elements
                          ▿ CopyFilesAction
                            - destination: Destination.productsDirectory
                            - files: 0 elements
                            - name: "Dependencies"
                            - subpath: Optional<String>.none
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                        - coreDataModels: 0 elements
                        ▿ dependencies: 2 elements
                          ▿ TargetDependency
                            ▿ target: (3 elements)
                              - name: "Bundle"
                              - status: LinkingStatus.required
                              - condition: Optional<PlatformCondition>.none
                          ▿ TargetDependency
                            ▿ target: (3 elements)
                              - name: "StaticFramework"
                              - status: LinkingStatus.required
                              - condition: Optional<PlatformCondition>.none
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "WidgetExtension"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: app extension
                        - productName: "WidgetExtension"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          ▿ resources: 1 element
                            ▿ ResourceFileElement
                              ▿ file: (3 elements)
                                - path: /Fixtures/ios_app_with_extensions/WidgetExtension/Resources/Assets.xcassets
                                - tags: 0 elements
                                - inclusionCondition: Optional<PlatformCondition>.none
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        ▿ sources: 3 elements
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistAssets+WidgetExtension.swift
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/ios_app_with_extensions/Derived/Sources/TuistBundle+WidgetExtension.swift
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/ios_app_with_extensions/WidgetExtension/Sources/Widget.swift
                  - packages: 0 elements
                  - schemes: 0 elements
                  ▿ settings: Settings
                    - base: 0 key/value pairs
                    - baseDebug: 0 key/value pairs
                    - configurations: 0 key/value pairs
                    ▿ defaultSettings: DefaultSettings
                      ▿ recommended: (1 element)
                        - excluding: 0 members
                  ▿ filesGroup: ProjectGroup
                    ▿ group: (1 element)
                      - name: "Project"
                  - additionalFiles: 0 elements
                  - ideTemplateMacros: Optional<IDETemplateMacros>.none
                  - resourceSynthesizers: 0 elements
                  - lastUpgradeCheck: Optional<Version>.none
                  - type: local project

            """
        }
    }
}
