import Foundation
import InlineSnapshotTesting
import Path
import Testing
import XcodeGraph
import XcodeProj
import XcodeProjMapper

extension IntegrationTests {
    @Test("Maps a macOS app with a system extension into the correct graph")
    func macosAppWithSystemExtension() throws {
        try assertGraph {
            .macosAppWithSystemExtension
        } name: {
            """
            - "App with SystemExtension"

            """
        } dependencies: {
            """
            ▿ 1 key/value pair
              ▿ (2 elements)
                ▿ key: target 'MainApp'
                  ▿ target: (3 elements)
                    - name: "MainApp"
                    - path: /Fixtures/macos_app_with_system_extension
                    - status: LinkingStatus.required
                ▿ value: 1 member
                  ▿ target 'SystemExtension'
                    ▿ target: (3 elements)
                      - name: "SystemExtension"
                      - path: /Fixtures/macos_app_with_system_extension
                      - status: LinkingStatus.required

            """
        } dependencyConditions: {
            """
            - 0 key/value pairs

            """
        } packages: {
            """
            - 0 key/value pairs

            """
        } workspace: {
            """
            ▿ Workspace
              - additionalFiles: 0 elements
              ▿ generationOptions: GenerationOptions
                ▿ autogeneratedWorkspaceSchemes: AutogeneratedWorkspaceSchemes
                  ▿ enabled: (5 elements)
                    - codeCoverageMode: CodeCoverageMode.disabled
                    ▿ testingOptions: TestingOptions
                      - rawValue: 0
                    - testLanguage: Optional<String>.none
                    - testRegion: Optional<String>.none
                    - testScreenCaptureFormat: Optional<ScreenCaptureFormat>.none
                ▿ enableAutomaticXcodeSchemes: Optional<Bool>
                  - some: false
                - lastXcodeUpgradeCheck: Optional<Version>.none
                - renderMarkdownReadme: false
              - ideTemplateMacros: Optional<IDETemplateMacros>.none
              - name: "App with SystemExtension"
              - path: /Fixtures/macos_app_with_system_extension
              ▿ projects: 1 element
                - /Fixtures/macos_app_with_system_extension/App with SystemExtension.xcodeproj
              - schemes: 0 elements
              - xcWorkspacePath: /Fixtures/macos_app_with_system_extension/App with SystemExtension.xcworkspace

            """
        } projects: {
            """
            ▿ 1 key/value pair
              ▿ (2 elements)
                - key: /Fixtures/macos_app_with_system_extension/App with SystemExtension.xcodeproj
                ▿ value: App with SystemExtension
                  - path: /Fixtures/macos_app_with_system_extension
                  - sourceRootPath: /Fixtures/macos_app_with_system_extension
                  - xcodeProjPath: /Fixtures/macos_app_with_system_extension
                  - name: "App with SystemExtension"
                  - organizationName: Optional<String>.none
                  - classPrefix: Optional<String>.none
                  ▿ defaultKnownRegions: Optional<Array<String>>
                    ▿ some: 2 elements
                      - "Base"
                      - "en"
                  ▿ developmentRegion: Optional<String>
                    - some: "en"
                  ▿ options: Options
                    - automaticSchemesOptions: AutomaticSchemesOptions.disabled
                    - disableBundleAccessors: false
                    - disableShowEnvironmentVarsInScriptPhases: false
                    - disableSynthesizedResourceAccessors: false
                    ▿ textSettings: TextSettings
                      - indentWidth: Optional<UInt>.none
                      - tabWidth: Optional<UInt>.none
                      - usesTabs: Optional<Bool>.none
                      - wrapsLines: Optional<Bool>.none
                  ▿ targets: 2 key/value pairs
                    ▿ (2 elements)
                      - key: "MainApp"
                      ▿ value: Target
                        ▿ additionalFiles: 3 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/macos_app_with_system_extension/Derived/InfoPlists/SystemExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/macos_app_with_system_extension/MainApp/Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/macos_app_with_system_extension/SystemExtension/Sources/main.swift
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.MainApp"
                        ▿ copyFiles: 2 elements
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                          ▿ CopyFilesAction
                            - destination: Destination.productsDirectory
                            - files: 0 elements
                            - name: "Embed System Extensions"
                            ▿ subpath: Optional<String>
                              - some: "$(CONTENTS_FOLDER_PATH)/Library/SystemExtensions"
                        - coreDataModels: 0 elements
                        ▿ dependencies: 1 element
                          ▿ TargetDependency
                            ▿ target: (3 elements)
                              - name: "SystemExtension"
                              - status: LinkingStatus.required
                              - condition: Optional<PlatformCondition>.none
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "MainApp"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: application
                        - productName: "MainApp"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          - resources: 0 elements
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        ▿ sources: 1 element
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/macos_app_with_system_extension/MainApp/Sources/main.swift
                        - type: TargetType.local
                    ▿ (2 elements)
                      - key: "SystemExtension"
                      ▿ value: Target
                        ▿ additionalFiles: 3 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/macos_app_with_system_extension/Derived/InfoPlists/SystemExtension-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/macos_app_with_system_extension/MainApp/Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/macos_app_with_system_extension/MainApp/Sources/main.swift
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.SystemExtension"
                        ▿ copyFiles: 1 element
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                        - coreDataModels: 0 elements
                        - dependencies: 0 elements
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "SystemExtension"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: system extension
                        - productName: "SystemExtension"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          - resources: 0 elements
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        ▿ sources: 1 element
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/macos_app_with_system_extension/SystemExtension/Sources/main.swift
                        - type: TargetType.local
                  - packages: 0 elements
                  - schemes: 0 elements
                  ▿ settings: Settings
                    - base: 0 key/value pairs
                    - baseDebug: 0 key/value pairs
                    - configurations: 0 key/value pairs
                    ▿ defaultSettings: DefaultSettings
                      ▿ recommended: (1 element)
                        - excluding: 0 members
                  ▿ filesGroup: ProjectGroup
                    ▿ group: (1 element)
                      - name: "Project"
                  - additionalFiles: 0 elements
                  - ideTemplateMacros: Optional<IDETemplateMacros>.none
                  - resourceSynthesizers: 0 elements
                  - lastUpgradeCheck: Optional<Version>.none
                  - type: local project

            """
        }
    }
}
