import Foundation
import InlineSnapshotTesting
import Path
import Testing
import XcodeGraph
import XcodeProj
import XcodeProjMapper

extension IntegrationTests {
    @Test("Maps an iOS app with multiple configurations into the correct graph")
    func iosAppWithMultiConfigs() throws {
        try assertGraph {
            .iosAppWithMultiConfigs
        } name: {
            """
            - "Workspace"

            """
        } dependencies: {
            """
            ▿ 3 key/value pairs
              ▿ (2 elements)
                ▿ key: target 'AppTests'
                  ▿ target: (3 elements)
                    - name: "AppTests"
                    - path: /Fixtures/ios_app_with_multi_configs/App
                    - status: LinkingStatus.required
                ▿ value: 1 member
                  ▿ target 'App'
                    ▿ target: (3 elements)
                      - name: "App"
                      - path: /Fixtures/ios_app_with_multi_configs/App
                      - status: LinkingStatus.required
              ▿ (2 elements)
                ▿ key: target 'Framework1Tests'
                  ▿ target: (3 elements)
                    - name: "Framework1Tests"
                    - path: /Fixtures/ios_app_with_multi_configs/Framework1
                    - status: LinkingStatus.required
                ▿ value: 1 member
                  ▿ target 'Framework1'
                    ▿ target: (3 elements)
                      - name: "Framework1"
                      - path: /Fixtures/ios_app_with_multi_configs/Framework1
                      - status: LinkingStatus.required
              ▿ (2 elements)
                ▿ key: target 'Framework2Tests'
                  ▿ target: (3 elements)
                    - name: "Framework2Tests"
                    - path: /Fixtures/ios_app_with_multi_configs/Framework2
                    - status: LinkingStatus.required
                ▿ value: 1 member
                  ▿ target 'Framework2'
                    ▿ target: (3 elements)
                      - name: "Framework2"
                      - path: /Fixtures/ios_app_with_multi_configs/Framework2
                      - status: LinkingStatus.required

            """
        } dependencyConditions: {
            """
            - 0 key/value pairs

            """
        } packages: {
            """
            - 0 key/value pairs

            """
        } workspace: {
            """
            ▿ Workspace
              - additionalFiles: 0 elements
              ▿ generationOptions: GenerationOptions
                ▿ autogeneratedWorkspaceSchemes: AutogeneratedWorkspaceSchemes
                  ▿ enabled: (5 elements)
                    - codeCoverageMode: CodeCoverageMode.disabled
                    ▿ testingOptions: TestingOptions
                      - rawValue: 0
                    - testLanguage: Optional<String>.none
                    - testRegion: Optional<String>.none
                    - testScreenCaptureFormat: Optional<ScreenCaptureFormat>.none
                ▿ enableAutomaticXcodeSchemes: Optional<Bool>
                  - some: false
                - lastXcodeUpgradeCheck: Optional<Version>.none
                - renderMarkdownReadme: false
              - ideTemplateMacros: Optional<IDETemplateMacros>.none
              - name: "Workspace"
              - path: /Fixtures/ios_app_with_multi_configs
              ▿ projects: 3 elements
                - /Fixtures/ios_app_with_multi_configs/App/MainApp.xcodeproj
                - /Fixtures/ios_app_with_multi_configs/Framework1/Framework1.xcodeproj
                - /Fixtures/ios_app_with_multi_configs/Framework2/Framework2.xcodeproj
              - schemes: 0 elements
              - xcWorkspacePath: /Fixtures/ios_app_with_multi_configs/Workspace.xcworkspace

            """
        } projects: {
            """
            ▿ 3 key/value pairs
              ▿ (2 elements)
                - key: /Fixtures/ios_app_with_multi_configs/App/MainApp.xcodeproj
                ▿ value: MainApp
                  - path: /Fixtures/ios_app_with_multi_configs/App
                  - sourceRootPath: /Fixtures/ios_app_with_multi_configs/App
                  - xcodeProjPath: /Fixtures/ios_app_with_multi_configs/App
                  - name: "MainApp"
                  - organizationName: Optional<String>.none
                  - classPrefix: Optional<String>.none
                  ▿ defaultKnownRegions: Optional<Array<String>>
                    ▿ some: 2 elements
                      - "Base"
                      - "en"
                  ▿ developmentRegion: Optional<String>
                    - some: "en"
                  ▿ options: Options
                    - automaticSchemesOptions: AutomaticSchemesOptions.disabled
                    - disableBundleAccessors: false
                    - disableShowEnvironmentVarsInScriptPhases: false
                    - disableSynthesizedResourceAccessors: false
                    ▿ textSettings: TextSettings
                      - indentWidth: Optional<UInt>.none
                      - tabWidth: Optional<UInt>.none
                      - usesTabs: Optional<Bool>.none
                      - wrapsLines: Optional<Bool>.none
                  ▿ targets: 2 key/value pairs
                    ▿ (2 elements)
                      - key: "App"
                      ▿ value: Target
                        ▿ additionalFiles: 6 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/App/Support/App-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/App/Support/AppTests-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/App/Tests/AppDelegateTests.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/ConfigurationFiles/Beta.xcconfig
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/ConfigurationFiles/Debug.xcconfig
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/ConfigurationFiles/Release.xcconfig
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.App"
                        ▿ copyFiles: 1 element
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                        - coreDataModels: 0 elements
                        - dependencies: 0 elements
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "App"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: application
                        - productName: "App"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          - resources: 0 elements
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        ▿ sources: 1 element
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/ios_app_with_multi_configs/App/Sources/AppDelegate.swift
                        - type: TargetType.local
                    ▿ (2 elements)
                      - key: "AppTests"
                      ▿ value: Target
                        ▿ additionalFiles: 6 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/App/Sources/AppDelegate.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/App/Support/App-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/App/Support/AppTests-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/ConfigurationFiles/Beta.xcconfig
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/ConfigurationFiles/Debug.xcconfig
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/ConfigurationFiles/Release.xcconfig
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.AppTests"
                        ▿ copyFiles: 1 element
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                        - coreDataModels: 0 elements
                        ▿ dependencies: 1 element
                          ▿ TargetDependency
                            ▿ target: (3 elements)
                              - name: "App"
                              - status: LinkingStatus.required
                              - condition: Optional<PlatformCondition>.none
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "AppTests"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: unit tests
                        - productName: "AppTests"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          - resources: 0 elements
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        ▿ sources: 1 element
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/ios_app_with_multi_configs/App/Tests/AppDelegateTests.swift
                        - type: TargetType.local
                  - packages: 0 elements
                  - schemes: 0 elements
                  ▿ settings: Settings
                    - base: 0 key/value pairs
                    - baseDebug: 0 key/value pairs
                    - configurations: 0 key/value pairs
                    ▿ defaultSettings: DefaultSettings
                      ▿ recommended: (1 element)
                        - excluding: 0 members
                  ▿ filesGroup: ProjectGroup
                    ▿ group: (1 element)
                      - name: "Project"
                  - additionalFiles: 0 elements
                  - ideTemplateMacros: Optional<IDETemplateMacros>.none
                  - resourceSynthesizers: 0 elements
                  - lastUpgradeCheck: Optional<Version>.none
                  - type: local project
              ▿ (2 elements)
                - key: /Fixtures/ios_app_with_multi_configs/Framework1/Framework1.xcodeproj
                ▿ value: Framework1
                  - path: /Fixtures/ios_app_with_multi_configs/Framework1
                  - sourceRootPath: /Fixtures/ios_app_with_multi_configs/Framework1
                  - xcodeProjPath: /Fixtures/ios_app_with_multi_configs/Framework1
                  - name: "Framework1"
                  - organizationName: Optional<String>.none
                  - classPrefix: Optional<String>.none
                  ▿ defaultKnownRegions: Optional<Array<String>>
                    ▿ some: 2 elements
                      - "Base"
                      - "en"
                  ▿ developmentRegion: Optional<String>
                    - some: "en"
                  ▿ options: Options
                    - automaticSchemesOptions: AutomaticSchemesOptions.disabled
                    - disableBundleAccessors: false
                    - disableShowEnvironmentVarsInScriptPhases: false
                    - disableSynthesizedResourceAccessors: false
                    ▿ textSettings: TextSettings
                      - indentWidth: Optional<UInt>.none
                      - tabWidth: Optional<UInt>.none
                      - usesTabs: Optional<Bool>.none
                      - wrapsLines: Optional<Bool>.none
                  ▿ targets: 2 key/value pairs
                    ▿ (2 elements)
                      - key: "Framework1"
                      ▿ value: Target
                        ▿ additionalFiles: 6 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/ConfigurationFiles/Beta.xcconfig
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/ConfigurationFiles/Debug.xcconfig
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/ConfigurationFiles/Release.xcconfig
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/Framework1/Support/Framework1-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/Framework1/Support/Framework1Tests-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/Framework1/Tests/Framework1FileTests.swift
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.Framework1"
                        ▿ copyFiles: 1 element
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                        - coreDataModels: 0 elements
                        - dependencies: 0 elements
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "Framework1"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: dynamic framework
                        - productName: "Framework1"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          - resources: 0 elements
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        ▿ sources: 1 element
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/ios_app_with_multi_configs/Framework1/Sources/Framework1File.swift
                        - type: TargetType.local
                    ▿ (2 elements)
                      - key: "Framework1Tests"
                      ▿ value: Target
                        ▿ additionalFiles: 6 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/ConfigurationFiles/Beta.xcconfig
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/ConfigurationFiles/Debug.xcconfig
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/ConfigurationFiles/Release.xcconfig
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/Framework1/Sources/Framework1File.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/Framework1/Support/Framework1-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/Framework1/Support/Framework1Tests-Info.plist
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.Framework1Tests"
                        ▿ copyFiles: 1 element
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                        - coreDataModels: 0 elements
                        ▿ dependencies: 1 element
                          ▿ TargetDependency
                            ▿ target: (3 elements)
                              - name: "Framework1"
                              - status: LinkingStatus.required
                              - condition: Optional<PlatformCondition>.none
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "Framework1Tests"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: unit tests
                        - productName: "Framework1Tests"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          - resources: 0 elements
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        ▿ sources: 1 element
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/ios_app_with_multi_configs/Framework1/Tests/Framework1FileTests.swift
                        - type: TargetType.local
                  - packages: 0 elements
                  - schemes: 0 elements
                  ▿ settings: Settings
                    - base: 0 key/value pairs
                    - baseDebug: 0 key/value pairs
                    - configurations: 0 key/value pairs
                    ▿ defaultSettings: DefaultSettings
                      ▿ recommended: (1 element)
                        - excluding: 0 members
                  ▿ filesGroup: ProjectGroup
                    ▿ group: (1 element)
                      - name: "Project"
                  - additionalFiles: 0 elements
                  - ideTemplateMacros: Optional<IDETemplateMacros>.none
                  - resourceSynthesizers: 0 elements
                  - lastUpgradeCheck: Optional<Version>.none
                  - type: local project
              ▿ (2 elements)
                - key: /Fixtures/ios_app_with_multi_configs/Framework2/Framework2.xcodeproj
                ▿ value: Framework2
                  - path: /Fixtures/ios_app_with_multi_configs/Framework2
                  - sourceRootPath: /Fixtures/ios_app_with_multi_configs/Framework2
                  - xcodeProjPath: /Fixtures/ios_app_with_multi_configs/Framework2
                  - name: "Framework2"
                  - organizationName: Optional<String>.none
                  - classPrefix: Optional<String>.none
                  ▿ defaultKnownRegions: Optional<Array<String>>
                    ▿ some: 2 elements
                      - "Base"
                      - "en"
                  ▿ developmentRegion: Optional<String>
                    - some: "en"
                  ▿ options: Options
                    - automaticSchemesOptions: AutomaticSchemesOptions.disabled
                    - disableBundleAccessors: false
                    - disableShowEnvironmentVarsInScriptPhases: false
                    - disableSynthesizedResourceAccessors: false
                    ▿ textSettings: TextSettings
                      - indentWidth: Optional<UInt>.none
                      - tabWidth: Optional<UInt>.none
                      - usesTabs: Optional<Bool>.none
                      - wrapsLines: Optional<Bool>.none
                  ▿ targets: 2 key/value pairs
                    ▿ (2 elements)
                      - key: "Framework2"
                      ▿ value: Target
                        ▿ additionalFiles: 7 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/ConfigurationFiles/Beta.xcconfig
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/ConfigurationFiles/Debug.xcconfig
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/ConfigurationFiles/Release.xcconfig
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/ConfigurationFiles/Target.Beta.xcconfig
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/Framework2/Support/Framework2-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/Framework2/Support/Framework2Tests-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/Framework2/Tests/Framework2FileTests.swift
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.Framework2"
                        ▿ copyFiles: 1 element
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                        - coreDataModels: 0 elements
                        - dependencies: 0 elements
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "Framework2"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: dynamic framework
                        - productName: "Framework2"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          - resources: 0 elements
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        ▿ sources: 1 element
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/ios_app_with_multi_configs/Framework2/Sources/Framework2File.swift
                        - type: TargetType.local
                    ▿ (2 elements)
                      - key: "Framework2Tests"
                      ▿ value: Target
                        ▿ additionalFiles: 7 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/ConfigurationFiles/Beta.xcconfig
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/ConfigurationFiles/Debug.xcconfig
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/ConfigurationFiles/Release.xcconfig
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/ConfigurationFiles/Target.Beta.xcconfig
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/Framework2/Sources/Framework2File.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/Framework2/Support/Framework2-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_multi_configs/Framework2/Support/Framework2Tests-Info.plist
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.Framework2Tests"
                        ▿ copyFiles: 1 element
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                        - coreDataModels: 0 elements
                        ▿ dependencies: 1 element
                          ▿ TargetDependency
                            ▿ target: (3 elements)
                              - name: "Framework2"
                              - status: LinkingStatus.required
                              - condition: Optional<PlatformCondition>.none
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "Framework2Tests"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: unit tests
                        - productName: "Framework2Tests"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          - resources: 0 elements
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        ▿ sources: 1 element
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/ios_app_with_multi_configs/Framework2/Tests/Framework2FileTests.swift
                        - type: TargetType.local
                  - packages: 0 elements
                  - schemes: 0 elements
                  ▿ settings: Settings
                    - base: 0 key/value pairs
                    - baseDebug: 0 key/value pairs
                    - configurations: 0 key/value pairs
                    ▿ defaultSettings: DefaultSettings
                      ▿ recommended: (1 element)
                        - excluding: 0 members
                  ▿ filesGroup: ProjectGroup
                    ▿ group: (1 element)
                      - name: "Project"
                  - additionalFiles: 0 elements
                  - ideTemplateMacros: Optional<IDETemplateMacros>.none
                  - resourceSynthesizers: 0 elements
                  - lastUpgradeCheck: Optional<Version>.none
                  - type: local project

            """
        }
    }
}
