import Foundation
import InlineSnapshotTesting
import Path
import Testing
import XcodeGraph
import XcodeProj
import XcodeProjMapper

extension IntegrationTests {
    @Test
    func projectNoWorkspace() throws {
        let path = try WorkspaceFixture.iosAppWithRemoteSwiftPackage.absolutePath().parentDirectory
            .appending(component: "App.xcodeproj")

        let parser = ProjectParser()
        let graph: XcodeGraph.Graph = try parser.parse(at: path.pathString)

        try #require(graph != nil)
    }

    @Test("Maps an iOS app with a remote Swift package into the correct graph")
    func iosAppWithRemoteSwiftPackage() throws {
        try assertGraph {
            .iosAppWithRemoteSwiftPackage
        } name: {
            """
            - "App"

            """
        } dependencies: {
            """
            ▿ 1 key/value pair
              ▿ (2 elements)
                ▿ key: target 'AppTests'
                  ▿ target: (3 elements)
                    - name: "AppTests"
                    - path: /Fixtures/ios_app_with_remote_swift_package
                    - status: LinkingStatus.required
                ▿ value: 1 member
                  ▿ target 'App'
                    ▿ target: (3 elements)
                      - name: "App"
                      - path: /Fixtures/ios_app_with_remote_swift_package
                      - status: LinkingStatus.required

            """
        } dependencyConditions: {
            """
            - 0 key/value pairs

            """
        } packages: {
            """
            ▿ 1 key/value pair
              ▿ (2 elements)
                - key: /Fixtures/ios_app_with_remote_swift_package/App.xcodeproj
                ▿ value: 1 key/value pair
                  ▿ (2 elements)
                    - key: "https://github.com/ReactiveX/RxSwift"
                    ▿ value: Package
                      ▿ remote: (2 elements)
                        - url: "https://github.com/ReactiveX/RxSwift"
                        ▿ requirement: Requirement
                          - upToNextMajor: "5.0.0"

            """
        } workspace: {
            """
            ▿ Workspace
              - additionalFiles: 0 elements
              ▿ generationOptions: GenerationOptions
                ▿ autogeneratedWorkspaceSchemes: AutogeneratedWorkspaceSchemes
                  ▿ enabled: (5 elements)
                    - codeCoverageMode: CodeCoverageMode.disabled
                    ▿ testingOptions: TestingOptions
                      - rawValue: 0
                    - testLanguage: Optional<String>.none
                    - testRegion: Optional<String>.none
                    - testScreenCaptureFormat: Optional<ScreenCaptureFormat>.none
                ▿ enableAutomaticXcodeSchemes: Optional<Bool>
                  - some: false
                - lastXcodeUpgradeCheck: Optional<Version>.none
                - renderMarkdownReadme: false
              - ideTemplateMacros: Optional<IDETemplateMacros>.none
              - name: "App"
              - path: /Fixtures/ios_app_with_remote_swift_package
              ▿ projects: 1 element
                - /Fixtures/ios_app_with_remote_swift_package/App.xcodeproj
              - schemes: 0 elements
              - xcWorkspacePath: /Fixtures/ios_app_with_remote_swift_package/App.xcworkspace

            """
        } projects: {
            """
            ▿ 1 key/value pair
              ▿ (2 elements)
                - key: /Fixtures/ios_app_with_remote_swift_package/App.xcodeproj
                ▿ value: App
                  - path: /Fixtures/ios_app_with_remote_swift_package
                  - sourceRootPath: /Fixtures/ios_app_with_remote_swift_package
                  - xcodeProjPath: /Fixtures/ios_app_with_remote_swift_package
                  - name: "App"
                  - organizationName: Optional<String>.none
                  - classPrefix: Optional<String>.none
                  ▿ defaultKnownRegions: Optional<Array<String>>
                    ▿ some: 2 elements
                      - "Base"
                      - "en"
                  ▿ developmentRegion: Optional<String>
                    - some: "en"
                  ▿ options: Options
                    - automaticSchemesOptions: AutomaticSchemesOptions.disabled
                    - disableBundleAccessors: false
                    - disableShowEnvironmentVarsInScriptPhases: false
                    - disableSynthesizedResourceAccessors: false
                    ▿ textSettings: TextSettings
                      - indentWidth: Optional<UInt>.none
                      - tabWidth: Optional<UInt>.none
                      - usesTabs: Optional<Bool>.none
                      - wrapsLines: Optional<Bool>.none
                  ▿ targets: 2 key/value pairs
                    ▿ (2 elements)
                      - key: "App"
                      ▿ value: Target
                        ▿ additionalFiles: 3 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_remote_swift_package/Support/Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_remote_swift_package/Support/Tests.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_remote_swift_package/Tests/AppTests.swift
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.App"
                        ▿ copyFiles: 1 element
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                        - coreDataModels: 0 elements
                        - dependencies: 0 elements
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "App"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: application
                        - productName: "App"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          - resources: 0 elements
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        ▿ sources: 1 element
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/ios_app_with_remote_swift_package/Sources/AppDelegate.swift
                        - type: TargetType.local
                    ▿ (2 elements)
                      - key: "AppTests"
                      ▿ value: Target
                        ▿ additionalFiles: 3 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_remote_swift_package/Sources/AppDelegate.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_remote_swift_package/Support/Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/ios_app_with_remote_swift_package/Support/Tests.plist
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.AppTests"
                        ▿ copyFiles: 1 element
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                        - coreDataModels: 0 elements
                        ▿ dependencies: 1 element
                          ▿ TargetDependency
                            ▿ target: (3 elements)
                              - name: "App"
                              - status: LinkingStatus.required
                              - condition: Optional<PlatformCondition>.none
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "AppTests"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: unit tests
                        - productName: "AppTests"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          - resources: 0 elements
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        ▿ sources: 1 element
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/ios_app_with_remote_swift_package/Tests/AppTests.swift
                        - type: TargetType.local
                  ▿ packages: 1 element
                    ▿ Package
                      ▿ remote: (2 elements)
                        - url: "https://github.com/ReactiveX/RxSwift"
                        ▿ requirement: Requirement
                          - upToNextMajor: "5.0.0"
                  - schemes: 0 elements
                  ▿ settings: Settings
                    - base: 0 key/value pairs
                    - baseDebug: 0 key/value pairs
                    - configurations: 0 key/value pairs
                    ▿ defaultSettings: DefaultSettings
                      ▿ recommended: (1 element)
                        - excluding: 0 members
                  ▿ filesGroup: ProjectGroup
                    ▿ group: (1 element)
                      - name: "Project"
                  - additionalFiles: 0 elements
                  - ideTemplateMacros: Optional<IDETemplateMacros>.none
                  - resourceSynthesizers: 0 elements
                  - lastUpgradeCheck: Optional<Version>.none
                  - type: local project

            """
        }
    }
}
