import Foundation
import InlineSnapshotTesting
import Path
import Testing
import XcodeGraph
import XcodeProj
import XcodeProjToGraph

@testable import TestSupport

extension IntegrationTests {
    @Test("Maps a multiplatform app with macros and an embedded watchOS app into the correct graph")
    func multiplatformAppWithMacrosAndEmbeddedWatchosApp() async throws {
        try await assertGraph {
            .multiplatformAppWithMacrosAndEmbeddedWatchosApp
        } name: {
            """
            - "AppWithWatchApp"

            """
        } dependencies: {
            """
            ▿ 4 key/value pairs
              ▿ (2 elements)
                ▿ key: target 'App'
                  ▿ target: (3 elements)
                    - name: "App"
                    - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app
                    - status: LinkingStatus.required
                ▿ value: 2 members
                  ▿ target 'ModuleA'
                    ▿ target: (3 elements)
                      - name: "ModuleA"
                      - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app
                      - status: LinkingStatus.required
                  ▿ target 'WatchApp'
                    ▿ target: (3 elements)
                      - name: "WatchApp"
                      - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app
                      - status: LinkingStatus.required
              ▿ (2 elements)
                ▿ key: target 'ModuleA'
                  ▿ target: (3 elements)
                    - name: "ModuleA"
                    - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app
                    - status: LinkingStatus.required
                ▿ value: 1 member
                  ▿ target 'ModuleAMacros'
                    ▿ target: (3 elements)
                      - name: "ModuleAMacros"
                      - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app
                      - status: LinkingStatus.required
              ▿ (2 elements)
                ▿ key: target 'ModuleATests'
                  ▿ target: (3 elements)
                    - name: "ModuleATests"
                    - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app
                    - status: LinkingStatus.required
                ▿ value: 2 members
                  ▿ target 'ModuleA'
                    ▿ target: (3 elements)
                      - name: "ModuleA"
                      - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app
                      - status: LinkingStatus.required
                  ▿ target 'ModuleAMacros_Testable'
                    ▿ target: (3 elements)
                      - name: "ModuleAMacros_Testable"
                      - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app
                      - status: LinkingStatus.required
              ▿ (2 elements)
                ▿ key: target 'WatchApp'
                  ▿ target: (3 elements)
                    - name: "WatchApp"
                    - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app
                    - status: LinkingStatus.required
                ▿ value: 1 member
                  ▿ target 'ModuleA'
                    ▿ target: (3 elements)
                      - name: "ModuleA"
                      - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app
                      - status: LinkingStatus.required

            """
        } dependencyConditions: {
            """
            ▿ 1 key/value pair
              ▿ (2 elements)
                ▿ key: GraphEdge
                  ▿ from: target 'App'
                    ▿ target: (3 elements)
                      - name: "App"
                      - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app
                      - status: LinkingStatus.required
                  ▿ to: target 'WatchApp'
                    ▿ target: (3 elements)
                      - name: "WatchApp"
                      - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app
                      - status: LinkingStatus.required
                ▿ value: PlatformCondition
                  ▿ platformFilters: 1 member
                    - PlatformFilter.ios

            """
        } packages: {
            """
            - 0 key/value pairs

            """
        } workspace: {
            """
            ▿ Workspace
              - additionalFiles: 0 elements
              ▿ generationOptions: GenerationOptions
                ▿ autogeneratedWorkspaceSchemes: AutogeneratedWorkspaceSchemes
                  ▿ enabled: (5 elements)
                    - codeCoverageMode: CodeCoverageMode.disabled
                    ▿ testingOptions: TestingOptions
                      - rawValue: 0
                    - testLanguage: Optional<String>.none
                    - testRegion: Optional<String>.none
                    - testScreenCaptureFormat: Optional<ScreenCaptureFormat>.none
                ▿ enableAutomaticXcodeSchemes: Optional<Bool>
                  - some: false
                - lastXcodeUpgradeCheck: Optional<Version>.none
                - renderMarkdownReadme: false
              - ideTemplateMacros: Optional<IDETemplateMacros>.none
              - name: "AppWithWatchApp"
              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app
              ▿ projects: 4 elements
                - /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/AppWithWatchApp.xcodeproj
                - /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Tuist/.build/tuist-derived/swift-case-paths/swift-case-paths.xcodeproj
                - /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Tuist/.build/tuist-derived/swift-syntax/swift-syntax.xcodeproj
                - /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Tuist/.build/tuist-derived/xctest-dynamic-overlay/xctest-dynamic-overlay.xcodeproj
              - schemes: 0 elements
              - xcWorkspacePath: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/AppWithWatchApp.xcworkspace

            """
        } projects: {
            """
            ▿ 1 key/value pair
              ▿ (2 elements)
                - key: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/AppWithWatchApp.xcodeproj
                ▿ value: AppWithWatchApp
                  - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app
                  - sourceRootPath: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app
                  - xcodeProjPath: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app
                  - name: "AppWithWatchApp"
                  - organizationName: Optional<String>.none
                  - classPrefix: Optional<String>.none
                  ▿ defaultKnownRegions: Optional<Array<String>>
                    ▿ some: 2 elements
                      - "Base"
                      - "en"
                  ▿ developmentRegion: Optional<String>
                    - some: "en"
                  ▿ options: Options
                    - automaticSchemesOptions: AutomaticSchemesOptions.disabled
                    - disableBundleAccessors: false
                    - disableShowEnvironmentVarsInScriptPhases: false
                    - disableSynthesizedResourceAccessors: false
                    ▿ textSettings: TextSettings
                      - indentWidth: Optional<UInt>.none
                      - tabWidth: Optional<UInt>.none
                      - usesTabs: Optional<Bool>.none
                      - wrapsLines: Optional<Bool>.none
                  ▿ targets: 6 key/value pairs
                    ▿ (2 elements)
                      - key: "App"
                      ▿ value: Target
                        ▿ additionalFiles: 15 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/App-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleA-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleAMacros-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleAMacros_Testable-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleATests-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistAssets+WatchApp.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistBundle+WatchApp.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Macros/Sources/Macros.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Sources/Macros.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Sources/ModuleA.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Tests/ModuleATests.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Sources/ContentView.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Sources/WatchApp.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Sources/WatchConfig.swift
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.App"
                        ▿ copyFiles: 2 elements
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                          ▿ CopyFilesAction
                            - destination: Destination.productsDirectory
                            - files: 0 elements
                            - name: "Embed Watch Content"
                            ▿ subpath: Optional<String>
                              - some: "$(CONTENTS_FOLDER_PATH)/Watch"
                        - coreDataModels: 0 elements
                        ▿ dependencies: 2 elements
                          ▿ TargetDependency
                            ▿ target: (3 elements)
                              - name: "ModuleA"
                              - status: LinkingStatus.required
                              - condition: Optional<PlatformCondition>.none
                          ▿ TargetDependency
                            ▿ target: (3 elements)
                              - name: "WatchApp"
                              - status: LinkingStatus.required
                              ▿ condition: Optional<PlatformCondition>
                                ▿ some: PlatformCondition
                                  ▿ platformFilters: 1 member
                                    - PlatformFilter.ios
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "App"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: application
                        - productName: "App"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          ▿ resources: 1 element
                            ▿ ResourceFileElement
                              ▿ file: (3 elements)
                                - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/App/Resources/Assets.xcassets
                                - tags: 0 elements
                                - inclusionCondition: Optional<PlatformCondition>.none
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        ▿ sources: 4 elements
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/App/Sources/ContentView.swift
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/App/Sources/TestApp.swift
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistAssets+App.swift
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistBundle+App.swift
                    ▿ (2 elements)
                      - key: "ModuleA"
                      ▿ value: Target
                        ▿ additionalFiles: 18 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/App/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/App/Sources/ContentView.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/App/Sources/TestApp.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/App-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleA-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleAMacros-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleAMacros_Testable-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleATests-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistAssets+App.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistAssets+WatchApp.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistBundle+App.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistBundle+WatchApp.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Macros/Sources/Macros.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Tests/ModuleATests.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Sources/ContentView.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Sources/WatchApp.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Sources/WatchConfig.swift
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.modulea"
                        ▿ copyFiles: 1 element
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                        - coreDataModels: 0 elements
                        ▿ dependencies: 1 element
                          ▿ TargetDependency
                            ▿ target: (3 elements)
                              - name: "ModuleAMacros"
                              - status: LinkingStatus.required
                              - condition: Optional<PlatformCondition>.none
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "ModuleA"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: dynamic framework
                        - productName: "ModuleA"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          - resources: 0 elements
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        ▿ sources: 2 elements
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Sources/Macros.swift
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Sources/ModuleA.swift
                    ▿ (2 elements)
                      - key: "ModuleAMacros"
                      ▿ value: Target
                        ▿ additionalFiles: 19 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/App/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/App/Sources/ContentView.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/App/Sources/TestApp.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/App-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleA-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleAMacros-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleAMacros_Testable-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleATests-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistAssets+App.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistAssets+WatchApp.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistBundle+App.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistBundle+WatchApp.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Sources/Macros.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Sources/ModuleA.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Tests/ModuleATests.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Sources/ContentView.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Sources/WatchApp.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Sources/WatchConfig.swift
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.moduleamacros"
                        ▿ copyFiles: 1 element
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                        - coreDataModels: 0 elements
                        - dependencies: 0 elements
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          ▿ macOS: Optional<String>
                            - some: "14.0"
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "ModuleAMacros"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: command line tool
                        - productName: "ModuleAMacros"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          - resources: 0 elements
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        ▿ sources: 1 element
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Macros/Sources/Macros.swift
                    ▿ (2 elements)
                      - key: "ModuleAMacros_Testable"
                      ▿ value: Target
                        ▿ additionalFiles: 19 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/App/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/App/Sources/ContentView.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/App/Sources/TestApp.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/App-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleA-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleAMacros-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleAMacros_Testable-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleATests-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistAssets+App.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistAssets+WatchApp.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistBundle+App.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistBundle+WatchApp.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Sources/Macros.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Sources/ModuleA.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Tests/ModuleATests.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Sources/ContentView.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Sources/WatchApp.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Sources/WatchConfig.swift
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.moduleamacros.testable"
                        ▿ copyFiles: 1 element
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                        - coreDataModels: 0 elements
                        - dependencies: 0 elements
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "ModuleAMacros_Testable"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: dynamic framework
                        - productName: "ModuleAMacros_Testable"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          - resources: 0 elements
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        ▿ sources: 1 element
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Macros/Sources/Macros.swift
                    ▿ (2 elements)
                      - key: "ModuleATests"
                      ▿ value: Target
                        ▿ additionalFiles: 19 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/App/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/App/Sources/ContentView.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/App/Sources/TestApp.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/App-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleA-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleAMacros-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleAMacros_Testable-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleATests-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistAssets+App.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistAssets+WatchApp.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistBundle+App.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistBundle+WatchApp.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Macros/Sources/Macros.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Sources/Macros.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Sources/ModuleA.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Sources/ContentView.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Sources/WatchApp.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Sources/WatchConfig.swift
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.moduleatests"
                        ▿ copyFiles: 1 element
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                        - coreDataModels: 0 elements
                        ▿ dependencies: 2 elements
                          ▿ TargetDependency
                            ▿ target: (3 elements)
                              - name: "ModuleA"
                              - status: LinkingStatus.required
                              - condition: Optional<PlatformCondition>.none
                          ▿ TargetDependency
                            ▿ target: (3 elements)
                              - name: "ModuleAMacros_Testable"
                              - status: LinkingStatus.required
                              - condition: Optional<PlatformCondition>.none
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "ModuleATests"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: unit tests
                        - productName: "ModuleATests"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          - resources: 0 elements
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        ▿ sources: 1 element
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Tests/ModuleATests.swift
                    ▿ (2 elements)
                      - key: "WatchApp"
                      ▿ value: Target
                        ▿ additionalFiles: 14 elements
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/App/Resources/Assets.xcassets
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/App/Sources/ContentView.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/App/Sources/TestApp.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/App-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleA-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleAMacros-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleAMacros_Testable-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/InfoPlists/ModuleATests-Info.plist
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistAssets+App.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistBundle+App.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Macros/Sources/Macros.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Sources/Macros.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Sources/ModuleA.swift
                          ▿ FileElement
                            ▿ file: (1 element)
                              - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Tests/ModuleATests.swift
                        - buildRules: 0 elements
                        - bundleId: "io.tuist.App.watchkitapp"
                        ▿ copyFiles: 1 element
                          ▿ CopyFilesAction
                            - destination: Destination.frameworks
                            - files: 0 elements
                            - name: "Embed Frameworks"
                            - subpath: Optional<String>.none
                        - coreDataModels: 0 elements
                        ▿ dependencies: 1 element
                          ▿ TargetDependency
                            ▿ target: (3 elements)
                              - name: "ModuleA"
                              - status: LinkingStatus.required
                              - condition: Optional<PlatformCondition>.none
                        ▿ deploymentTargets: DeploymentTargets
                          - iOS: Optional<String>.none
                          - macOS: Optional<String>.none
                          - tvOS: Optional<String>.none
                          - visionOS: Optional<String>.none
                          - watchOS: Optional<String>.none
                        - destinations: 0 members
                        - entitlements: Optional<Entitlements>.none
                        - environmentVariables: 0 key/value pairs
                        ▿ filesGroup: ProjectGroup
                          ▿ group: (1 element)
                            - name: "MainGroup"
                        - headers: Optional<Headers>.none
                        - infoPlist: Optional<InfoPlist>.none
                        - launchArguments: 0 elements
                        - mergeable: false
                        - mergedBinaryType: MergedBinaryType.disabled
                        ▿ metadata: TargetMetadata
                          - tags: 0 members
                        - name: "WatchApp"
                        - onDemandResourcesTags: Optional<OnDemandResourcesTags>.none
                        - playgrounds: 0 elements
                        - product: application
                        - productName: "WatchApp"
                        - prune: false
                        - rawScriptBuildPhases: 0 elements
                        ▿ resources: ResourceFileElements
                          - privacyManifest: Optional<PrivacyManifest>.none
                          ▿ resources: 1 element
                            ▿ ResourceFileElement
                              ▿ file: (3 elements)
                                - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Resources/Assets.xcassets
                                - tags: 0 elements
                                - inclusionCondition: Optional<PlatformCondition>.none
                        - scripts: 0 elements
                        - settings: Optional<Settings>.none
                        ▿ sources: 5 elements
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistAssets+WatchApp.swift
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Derived/Sources/TuistBundle+WatchApp.swift
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Sources/ContentView.swift
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Sources/WatchApp.swift
                          ▿ SourceFile
                            - codeGen: Optional<FileCodeGen>.none
                            - compilationCondition: Optional<PlatformCondition>.none
                            - compilerFlags: Optional<String>.none
                            - contentHash: Optional<String>.none
                            - path: /Fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Sources/WatchConfig.swift
                  - packages: 0 elements
                  - schemes: 0 elements
                  ▿ settings: Settings
                    - base: 0 key/value pairs
                    - baseDebug: 0 key/value pairs
                    - configurations: 0 key/value pairs
                    ▿ defaultSettings: DefaultSettings
                      ▿ recommended: (1 element)
                        - excluding: 0 members
                  ▿ filesGroup: ProjectGroup
                    ▿ group: (1 element)
                      - name: "Project"
                  - additionalFiles: 0 elements
                  - ideTemplateMacros: Optional<IDETemplateMacros>.none
                  - resourceSynthesizers: 0 elements
                  - lastUpgradeCheck: Optional<Version>.none
                  - type: local project

            """
        }
    }
}
