name: Docs

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: docs-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Setup Swift
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: 6.0.3
      - name: Build docs
        run: mise run docs:build
